### ISSUE TITLE
Conflict with Levels

### ISSUE THREAD

**Issue by Fridan99** [WesBelmont/token-lean#1]
Foundry 0.98.249
System dnd5e 1.5.7
Token Lean: Peek Around Corners 1.0.2
Levels 2.5 (and its dependencies below) 
betterroofs 1.3.8
libwrapper 1.12.3.0
wall-height 3.6.0.2

Other different modules active: FALSE

--------------------
It seems that the module does not work with Levels.

Screenshot GM Vision
![Vision GM](https://user-images.githubusercontent.com/86131373/154800686-a4719934-2f08-4199-9691-e204bb7c8d98.jpg)

Screenshot PC Vision (Token Lean without pressing q key)
![Vision PC (deactivate)](https://user-images.githubusercontent.com/86131373/154800717-c2a6a3c2-cedb-4de9-8671-f1f51d95b0aa.jpg)

Screenshot PC Vision (Token Lean pressing q key)    (The tokens behind the wall are not visible)
![Vision PC (activate) Levels](https://user-images.githubusercontent.com/86131373/154800731-cb545e02-dd97-4567-a934-f6d85bb28c99.jpg)

**Comment by WesBelmont** [comment]
I have not used Levels before but I'll look into it. It may take a while to figure out though. I know that Levels is very popular so making this compatible will be a priority.

**Comment by WesBelmont** [comment]
I have found a solution. Levels provides an override for the LOS check. I just need to change the origin from the token's center to the token's vision. I don't have the time to implement a fix now, but I expect to have it done early next week.

**Comment by WesBelmont** [comment]
It should be fixed now. Update is live.

**Comment by WesBelmont** [comment]
It stopped working when I published.... back to bugfixing

**Comment by WesBelmont** [comment]
Well, after two hours of struggling with github and vscode not working nicely together. It is up and running and as far as I can tell, with no errors.
