### ISSUE TITLE
Token Invisibility Compromised When Using Levels and Wall Height

### ISSUE THREAD

**Issue by Dialectikal** [WesBelmont/token-lean#10]
Ok, so it looks like it has been resolved for most cases. The issue only seems to occur when vision is removed from a player's primary token, or when their token is made invisible:
![image](https://user-images.githubusercontent.com/31572084/164885071-59eaf288-0600-4ac1-88f3-f4ff3c4de6fb.png)

This is probably why you aren't seeing it in your tests. Most of the time, my players won't be able to see the other tokens. But a lot of people use the invisibility functionality to move players around between areas or to signify being blinded or in darkness. In my case, I was using it to record sessions and to test player functionality. That's why it showed up in my previous screenshot, even though there was still vision.

The walls are standard, with the maximum range set for Wall Height. The map itself has been in use for a few months without any change to the walls.

Not sure if that helps or not. Please let me know if you want me to check anything else.

_Originally posted by @Dialectikal in https://github.com/WesBelmont/token-lean/issues/9#issuecomment-1107416330_

**Comment by WesBelmont** [comment]
This appears to be a bug with Levels. The issue exists even when Token Lean is disabled. Could you submit a bug report on their page?

**Comment by Dialectikal** [comment]
Ok, will do
