### ISSUE TITLE
Replace `token.center` with `token.getSightOrigin()`

### ISSUE THREAD

**Issue by dev7355608** [WesBelmont/token-lean#11]
`token.getSightOrigin()` is slightly different from `token.center` to prevent tokens from moving/seeing through walls that bisect the grid space.  Token Lean using `token.center` allows tokens to see though walls in those situations:

![tokenlean](https://user-images.githubusercontent.com/31905376/166802863-bcebf8f1-c233-4faf-880f-07f62b512ab9.gif)

**Comment by mkahvi** [comment]
This is even more common problem for large tokens.

**Comment by WesBelmont** [comment]
I'm using getMovementAdjustedPoint now which has improved the behaviour, but there seem to be some edge cases (literally) in core.

**Comment by mkahvi** [comment]
Seems to work much better than before. I noticed one test case where I managed to see through a wall, but I couldn't reproduce it.
