### ISSUE TITLE
Differentiate between Scene Darkness and Total Darkness.

### ISSUE THREAD

**Issue by Verthiss** [WesBelmont/token-lean#13]
Hi!
It would be great if the module could differentiate between Scene Darkness and Total Darkness modes of view. Right now if a character has Dim Vision set to Scene Darkness and uses Token Leen, his vision changes to Total Darkness (aka, he cannot see in darkness anymore). This might be a thing of compatibility with the Perfect Vision because I'm not sure if Foundry differentiates between those modes of vision without it, but anyways, would be great to have fixed.
Anyways, awesome mod, keep it up!

**Comment by WesBelmont** [comment]
Is this still an issue in v10? There shouldn't be anything that changes the vision modes in this module. Just position data. If it is still an issue, I'l invesigate further and reopen the issue.
