### ISSUE TITLE
Broken with v10

### ISSUE THREAD

**Issue by mkahvi** [WesBelmont/token-lean#16]
Lots of errors about radial sweep when attempting to use with nothing happening.

Love this module, so I hope you'll fix it up :)

**Comment by SgtSmith95** [comment]
+1 was great for more tactical/horror based games

**Comment by WesBelmont** [comment]
I'll have some time to work on it soon. I'm really glad it has been useful, and sorry I haven't updated it in a while.

**Comment by Fridan99** [comment]
that's good news... great, this is one of those modules which is why I haven't upgraded to v10 yet.... I think it's ESSENTIAL. Thx bro
